supabase:
  url: ${SUPABASE_URL}
  anon: ${SUPABASE_ANON_KEY}
  jwt_secret: ${SUPABASE_JWT_SIGNER}
spring:
  datasource:
    url: ${SUPABASE_DATABASE_URL}
    username: ${SUPABASE_DATABASE_USER}
    password: ${SUPABASE_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always